//
// Created by Usuario on 11/10/2024.
//

#ifndef MAIN5_H
#define MAIN5_H


void lanzaExcepcion() {
    throw std::runtime_error("Error en la funci√≥n lanzaExcepcion");
}


#endif //MAIN5_H
