//
// Created by Usuario on 11/10/2024.
//

#ifndef MAIN6_H
#define MAIN6_H



void lanzaExcepcion() {
    throw std::runtime_error("Error en la funci√≥n lanzaExcepcion");
}



#endif //MAIN6_H
